package org.usac.calculadora;

/**
 *
 * @author esvux
 */
public class FormularioCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCalculadora
     */
    public FormularioCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldA = new javax.swing.JTextField();
        jTextFieldB = new javax.swing.JTextField();
        jButtonSUM = new javax.swing.JButton();
        jButtonRES = new javax.swing.JButton();
        jButtonMUL = new javax.swing.JButton();
        jButtonDIV = new javax.swing.JButton();
        jLabelRESULTADO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldA.setFont(new java.awt.Font("Droid Sans", 0, 24)); // NOI18N

        jTextFieldB.setFont(new java.awt.Font("Droid Sans", 0, 24)); // NOI18N

        jButtonSUM.setFont(new java.awt.Font("Droid Sans Mono", 0, 24)); // NOI18N
        jButtonSUM.setText("+");
        jButtonSUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSUMActionPerformed(evt);
            }
        });

        jButtonRES.setFont(new java.awt.Font("Droid Sans Mono", 0, 24)); // NOI18N
        jButtonRES.setText("-");
        jButtonRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESActionPerformed(evt);
            }
        });

        jButtonMUL.setFont(new java.awt.Font("Droid Sans Mono", 0, 24)); // NOI18N
        jButtonMUL.setText("*");
        jButtonMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMULActionPerformed(evt);
            }
        });

        jButtonDIV.setFont(new java.awt.Font("Droid Sans Mono", 0, 24)); // NOI18N
        jButtonDIV.setText("/");
        jButtonDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDIVActionPerformed(evt);
            }
        });

        jLabelRESULTADO.setFont(new java.awt.Font("Droid Sans", 0, 24)); // NOI18N
        jLabelRESULTADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSUM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRES, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMUL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelRESULTADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSUM)
                    .addComponent(jButtonRES)
                    .addComponent(jButtonMUL)
                    .addComponent(jButtonDIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRESULTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSUMActionPerformed
        Integer suma = new Calculadora(getA(), getB()).sumar();
        jLabelRESULTADO.setText("Suma: "+ suma);
    }//GEN-LAST:event_jButtonSUMActionPerformed

    private void jButtonRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESActionPerformed
        Integer resta = new Calculadora(getA(), getB()).restar();
        jLabelRESULTADO.setText("Resta: "+ resta);
    }//GEN-LAST:event_jButtonRESActionPerformed

    private void jButtonMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMULActionPerformed
        Integer multi = new Calculadora(getA(), getB()).multiplicar();
        jLabelRESULTADO.setText("Multiplicacion: "+ multi);
    }//GEN-LAST:event_jButtonMULActionPerformed

    private void jButtonDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDIVActionPerformed
        Double div = new Calculadora(getA(), getB()).dividir();
        jLabelRESULTADO.setText("Division: "+ div);
    }//GEN-LAST:event_jButtonDIVActionPerformed

    private Integer getA(){
        return Integer.parseInt(jTextFieldA.getText());
    }
    
    private Integer getB(){
        return Integer.parseInt(jTextFieldA.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDIV;
    private javax.swing.JButton jButtonMUL;
    private javax.swing.JButton jButtonRES;
    private javax.swing.JButton jButtonSUM;
    private javax.swing.JLabel jLabelRESULTADO;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    // End of variables declaration//GEN-END:variables
}
